Repository alinix1/rancid-tomatillos, pull requests merged in 2022-10, with the labels that each got.

#11 Feature/display all movies
  src/App.css
  src/App.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/App/movieData.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Movies/Movies.css
  src/components/Movies/Movies.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
  src/index.js
Labels: iteration 1

#12 add functionality to show single movie and main page along with CSS h…
  src/components/App/App.js
  src/components/App/movieData.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Movies/Movies.js
  src/components/SingleMovie/SingleMovie.js
Labels: iteration 2

#13 Feature/get fetch
  src/apiCalls.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Movies/Movies.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: iteration 3

#14 add CSS to components
  package-lock.json
  package.json
  src/components/App/App.css
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Movies/Movies.css
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: styling

#17 Refactor/error handling
  src/assets/refresh.png
  src/assets/tomatillo.png
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/SingleMovie/SingleMovie.js
  src/logo.svg
Labels: iteration 3, styling

#27 Feature/router setup
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Movies/Movies.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
  src/index.js
Labels: iteration 4

#28 add cypress testing suite for allMovies
  cypress.config.js
  cypress/e2e/allMovies_spec.cy.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
Labels: iteration 4

#30 Testing/add cypress tests
  cypress/e2e/allMovies_spec.cy.js
  cypress/e2e/singleMovie_spec.cy.js
  cypress/e2e/spec.cy.js
  package.json
  src/apiCalls.js
  src/components/App/App.js
  src/components/SingleMovie/SingleMovie.js
Labels: iteration 4

#31 Testing/add stubs
  cypress/e2e/allMovieErrors_spec.cy.js
  cypress/e2e/allMovies_spec.cy.js
  cypress/e2e/singleMovieErrors_spec.cy.js
  cypress/e2e/singleMovie_spec.cy.js
  src/assets/close.png
  src/components/App/App.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: iteration 4

#33 Feature/search bar
  cypress/e2e/allMovies_spec.cy.js
  public/index.html
  public/logo512.png
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Movies/Movies.css
  src/components/Movies/Movies.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: iteration 5
